version: 2
jobs:
  build:
    working_directory: ~/circleci-2.0-pytest-postgresql
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
        environment:
          DATABASE_URL: postgres://ubuntu@localhost:5432/circle_test
      - image: circleci/postgres:9.6.5-alpine-ram
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client-9.6
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install Requirements
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Setup the database
          command: psql -h localhost -p 5432 -U ubuntu -d circle_test -a -f schema.sql
      - run:
          name: Run the Tests
          command: |
            . venv/bin/activate
            py.test tests --junitxml=test-reports/output.xml
      - store_artifacts:
          path: test-reports/
          destination: tr1
      - store_test_results:
          path: test-reports/
